<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		
		<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.13" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
		<PackageReference Include="FluentAssertions" Version="8.8.0" />
		<PackageReference Include="Moq" Version="4.20.72" />
		
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BinMaps.API\BinMaps.API.csproj" />
		<ProjectReference Include="..\BinMaps.Data\BinMaps.Data.csproj" />
		<ProjectReference Include="..\BinMaps.Infrastructure\BinMaps.Infrastructure.csproj" />
		<ProjectReference Include="..\BinMaps.Shared\BinMaps.Shared.csproj" />
		
	</ItemGroup>

</Project>