version: "3.9"

services:

  ai:
    build:
      context: .
      dockerfile: BinMaps.AI/Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: BinMaps.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=169.197.183.12;Database=kzpmg_binmaps;User Id=binmapsUser;Password=ТУК_ПАРОЛАТА;TrustServerCertificate=true;Trusted_Connection=False;"
      AISettings__Endpoint: "http://ai:8000/analyze"
      AllowedOrigins: "http://binmaps.kzpmg.com/"
    depends_on:
      - ai
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: BinMaps.UI/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped