services:

  ai:
    build:
      context: .
      dockerfile: BinMaps.AI/Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: BinMaps.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=169.197.183.12;Database=kzpmg_binmaps;User Id=binmapsUser;Password=hB_$$Nu79nmwj4Ubi;TrustServerCertificate=true;Trusted_Connection=False;"
      AISettings__Endpoint: "http://ai:8000/analyze"
      AllowedOrigins: "http://95.111.238.194"
      Jwt__Key: "b1nM@psS3cr3tK3y!2026#Secure1234567890"
      Jwt__Issuer: "BinMapsAPI"
      Jwt__Audience: "BinMapsClient"
    depends_on:
      - ai
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: BinMaps.UI/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped