// <auto-generated />
using System;
using BinMaps.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BinMaps.Data.Migrations
{
    [DbContext(typeof(BinMapsDbContext))]
    [Migration("20260228000000_MakeIsApprovedNullable")]
    partial class MakeIsApprovedNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            // Snapshot is maintained in BinMapsDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
