FROM python:3.11-slim
WORKDIR /app


RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY BinMaps.AI/requirements.txt .

RUN pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir -r requirements.txt

COPY BinMaps.AI/ .

EXPOSE 8000
ENV MODEL_PATH=/app/bin_fill_model.pth

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]