name: Trigger auto deployment for binmaps-b

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/binmaps-b-AutoDeployTrigger-c3aaee8e-041f-4d5b-82ce-5f7a744425a7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BINMAPSB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BINMAPSB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BINMAPSB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: binmapsacr.azurecr.io
          registryUsername: ${{ secrets.BINMAPSB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BINMAPSB_REGISTRY_PASSWORD }}
          containerAppName: binmaps-b
          resourceGroup: binmaps-rg
          imageToBuild: binmapsacr.azurecr.io/binmaps-b:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


